// Ref: ISO 14229-1 UDS standard

/**
 * UDS service identifiers (SIDs).
 * Ref: ISO 14229-1 §11 — Service definitions
 */
export const UDS_SERVICES = {
	DIAGNOSTIC_SESSION_CONTROL: 0x10,
	ECU_RESET: 0x11,
	SECURITY_ACCESS: 0x27,
	COMMUNICATION_CONTROL: 0x28,
	TESTER_PRESENT: 0x3e,
	READ_DATA_BY_IDENTIFIER: 0x22,
	READ_MEMORY_BY_ADDRESS: 0x23,
	WRITE_DATA_BY_IDENTIFIER: 0x2e,
	WRITE_MEMORY_BY_ADDRESS: 0x3d,
	REQUEST_DOWNLOAD: 0x34,
	TRANSFER_DATA: 0x36,
	REQUEST_TRANSFER_EXIT: 0x37,
	ERASE_MEMORY: 0xff, // manufacturer-specific
} as const;

/**
 * UDS diagnostic session types.
 * Ref: ISO 14229-1 §9.2 — DiagnosticSessionControl
 */
export const UDS_SESSION_TYPES = {
	DEFAULT: 0x01,
	PROGRAMMING: 0x02,
	EXTENDED_DIAGNOSTIC: 0x03,
} as const;

/**
 * UDS negative response service identifier.
 * Ref: ISO 14229-1 §11.3 — NegativeResponse
 */
export const UDS_NEGATIVE_RESPONSE = 0x7f;

/**
 * UDS negative response codes (NRC).
 * Ref: ISO 14229-1 §11.3.2 — NRC definitions
 */
export const UDS_NRC = {
	GENERAL_REJECT: 0x10,
	SERVICE_NOT_SUPPORTED: 0x11,
	SUB_FUNCTION_NOT_SUPPORTED: 0x12,
	INCORRECT_MESSAGE_LENGTH: 0x13,
	CONDITIONS_NOT_CORRECT: 0x22,
	REQUEST_SEQUENCE_ERROR: 0x24,
	REQUEST_OUT_OF_RANGE: 0x31,
	SECURITY_ACCESS_DENIED: 0x33,
	INVALID_KEY: 0x35,
	EXCEEDED_NUMBER_OF_ATTEMPTS: 0x36,
	REQUIRED_TIME_DELAY_NOT_EXPIRED: 0x37,
	UPLOAD_DOWNLOAD_NOT_ACCEPTED: 0x70,
	TRANSFER_DATA_SUSPENDED: 0x71,
	GENERAL_PROGRAMMING_FAILURE: 0x72,
	WRONG_BLOCK_SEQUENCE_COUNTER: 0x73,
	RESPONSE_PENDING: 0x78,
	SUB_FUNCTION_NOT_SUPPORTED_IN_ACTIVE_SESSION: 0x7e,
	SERVICE_NOT_SUPPORTED_IN_ACTIVE_SESSION: 0x7f,
} as const;
